apiVersion: ml.jay.dev/v1
kind: TrainingJob
metadata:
  name: test-concurrent-1
spec:
  image: busybox
  command: ["sh", "-c"]
  args: ["echo job 1 started; sleep 5; echo job 1 done"]
  maxRetries: 1
