apiVersion: ml.jay.dev/v1
kind: TrainingJob
metadata:
  name: retry-trainingjob
  namespace: default
spec:
  image: trainer:dev
  args:
    - --epochs=2
  env:
    - name: FAIL_TRAINING
      value: "1"
  maxRetries: 3
